////
Copyright Terracotta, Inc.
Copyright IBM Corp. 2024, 2025

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
////

= BigMemory Core  Storage

BigMemory Core Storage is a skin around the offheap-store library that
abstracts away some of the complexity of construction seen in offheap-store.
What is left is a library with a simpler configuration interface that is limited
to only the functionality required by the Terracotta server instances that
depend on this library.

== What Can I Do With This

The basic gateway is to construct an +OffHeapStorageManager+ instance from which
you can create, retrieve and destroy +KeyValueStorage+ instances (maps).
Configurations can be constructed using the +ImmutableKeyValueStorageConfig.builder(...)+
method.  If you want to control the way that objects are serialized beyond the
default behavior then you can pass a TransformerLookup instance in to the
storage manager at construction time.
