////
The contents of this file are subject to the Terracotta Public License Version
2.0 (the "License"); You may not use this file except in compliance with the
License. You may obtain a copy of the License at 

     http://terracotta.org/legal/terracotta-public-license.

Software distributed under the License is distributed on an "AS IS" basis,
WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
the specific language governing rights and limitations under the License.

The Covered Software is BigMemory Core Storage Implementation.

The Initial Developer of the Covered Software is 
     Terracotta, Inc., a Software AG company
////

= BigMemory Core  Storage

BigMemory Core Storage is a skin around the offheap-store library that
abstracts away some of the complexity of construction seen in offheap-store.
What is left is a library with a simpler configuration interface that is limited
to only the functionality required by the Terracotta server instances that
depend on this library.

== What Can I Do With This

The basic gateway is to construct an +OffHeapStorageManager+ instance from which
you can create, retrieve and destroy +KeyValueStorage+ instances (maps).
Configurations can be constructed using the +ImmutableKeyValueStorageConfig.builder(...)+
method.  If you want to control the way that objects are serialized beyond the
default behavior then you can pass a TransformerLookup instance in to the
storage manager at construction time.
